$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: online-deployment-diabetes-green
description: A deployment using sklaern to predict diabetes.
endpoint_name: online-endpoint-diabetes
model: azureml:supportvectorclassifier@latest
code_configuration:
  code: .
  scoring_script: main.py
environment_variables:
  TEST_KEY: TEST_VALUE
environment:
  conda_file: ./conda.yml
  image: mcr.microsoft.com/azureml/mlflow-ubuntu20.04-py38-cpu-inference:20240522.v1
instance_type: Standard_D2as_v4
instance_count: 1
app_insights_enabled: true
scale_settings:
  type: default
request_settings:
  request_timeout_ms: 5000
  max_concurrent_requests_per_instance: 1
  max_queue_wait_ms: 500
liveness_probe:
  initial_delay: 10
  period: 10
  timeout: 2
  success_threshold: 1
  failure_threshold: 10
readiness_probe:
  initial_delay: 10
  period: 10
  timeout: 2
  success_threshold: 1
  failure_threshold: 10
# data_collector:
#   enabled: true
#   destination:
#     path: azureml://datastores/workspaceblobstore/paths/online-endpoints
egress_public_network_access: enabled
# private_network_connection: false
