name: Azure ML Training Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
    secrets:
      TENANT_ID:
        required: true
        description: "Specifies the tenant id of the deployment."
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      SUBSCRIPTION_ID:
        required: true
        description: "Specifies the client id."
    outputs:
      job_name:
        description: "The name of the machine learning job."
        value: ${{ jobs.train.outputs.job_name }}

permissions:
  id-token: write
  contents: read

env:
  AZURE_ML_WORKSPACE_NAME: aml-ws-mlops
  AZURE_RESOURCE_GROUP_NAME: rg-mlops

jobs:
  train:
    name: Train model in ${{ inputs.environment }}
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: ${{ inputs.environment }}
    outputs:
      job_name: ${{ steps.aml_job.outputs.job_name }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Login to Azure
      - name: Azure Login
        id: azure_login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      # Install ML extension
      - name: Install ML Extension
        id: aml_install
        run: |
          az extension add -n ml

      # Create Dataset
      - name: Create Dataset
        id: aml_dataset
        run: |
          az ml data create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
            --workspace-name ${{ env.AZURE_ML_WORKSPACE_NAME }} \
            --file ${{ github.workspace }}/code/ml/data/diabetes_mltable.yml

      # Create Job
      - name: Create Job
        id: aml_job
        run: |
          az ml job create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
            --workspace-name ${{ env.AZURE_ML_WORKSPACE_NAME }} \
            --name $JOB_NAME \
            --file ${{ github.workspace }}/code/ml/pipeline-train.yml \
            --stream
        env:
          JOB_NAME: "Job-${{ github.sha }}"

      # Log out from Azure
      - name: Log out from Azure
        id: azure_logout
        uses: azure/cli@v1
        with:
          azcliversion: "agentazcliversion"
          inlineScript: |
            az logout
