name: Dev Deployment
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/ml/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/ml/**"

env:
  workspace-name: aml-ws-mlops
  resource-group: rg-mlops
  
permissions:
  id-token: write
  contents: read

jobs:

  # aml_training_dev:
  #   uses: ./.github/workflows/_amlTrainTemplate.yml
  #   name: "Azure ML Training - Dev"
  #   if: github.event_name == 'push' || github.event_name == 'release'
  #   with:
  #     environment: "dev"
  #   secrets:
  #     TENANT_ID: ${{ secrets.TENANT_ID }}
  #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
  #     SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

  aml_deploy_dev:
    uses: ./.github/workflows/_amlDeployTemplate.yml
    name: "Azure ML Deploy - Dev"
    #needs: [aml_training_dev]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
      resource_group: "rg-mlops"
      workspace_name: "aml-ws-mlops"
      machine_learning_online_endpoint_name: "online-endpoint-diabetes"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

  # aml_model_promotion_dev_to_prd:
  #   uses: ./.github/workflows/_amlModelPromotionTemplate.yml
  #   name: "Azure ML Model Promotion - Dev to Prod"
  #   needs: [aml_training_dev]
  #   if: github.event_name == 'push' || github.event_name == 'release'
  #   with:
  #     environment_source: "dev"
  #     environment_destination: "prd"
  #     job_name: ${{ needs.aml_training_dev.outputs.job_name }}
  #     output_name: best_model
  #   secrets:
  #     TENANT_ID: ${{ secrets.TENANT_ID }}
  #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
